/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProvidersRouteImport } from './routes/_app.providers'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClinicsRouteImport } from './routes/_app.clinics'
import { Route as AppCallCenterRouteImport } from './routes/_app.call-center'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppCallCenterWhatsappTemplatesRouteImport } from './routes/_app.call-center.whatsapp-templates'
import { Route as AppCallCenterWhatsappRouteImport } from './routes/_app.call-center.whatsapp'
import { Route as AppCallCenterPersonaRouteImport } from './routes/_app.call-center.persona'
import { Route as AppCallCenterKnowledgeBaseRouteImport } from './routes/_app.call-center.knowledge-base'
import { Route as AppCallCenterHistoryRouteImport } from './routes/_app.call-center.history'
import { Route as AppCallCenterDashboardRouteImport } from './routes/_app.call-center.dashboard'
import { Route as AppCallCenterConfigurationRouteImport } from './routes/_app.call-center.configuration'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicsRoute = AppClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AppRoute,
} as any)
const AppCallCenterRoute = AppCallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppCallCenterWhatsappTemplatesRoute =
  AppCallCenterWhatsappTemplatesRouteImport.update({
    id: '/whatsapp-templates',
    path: '/whatsapp-templates',
    getParentRoute: () => AppCallCenterRoute,
  } as any)
const AppCallCenterWhatsappRoute = AppCallCenterWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppCallCenterRoute,
} as any)
const AppCallCenterPersonaRoute = AppCallCenterPersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => AppCallCenterRoute,
} as any)
const AppCallCenterKnowledgeBaseRoute =
  AppCallCenterKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AppCallCenterRoute,
  } as any)
const AppCallCenterHistoryRoute = AppCallCenterHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppCallCenterRoute,
} as any)
const AppCallCenterDashboardRoute = AppCallCenterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppCallCenterRoute,
} as any)
const AppCallCenterConfigurationRoute =
  AppCallCenterConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => AppCallCenterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AppAppointmentsRoute
  '/calendar': typeof AppCalendarRoute
  '/call-center': typeof AppCallCenterRouteWithChildren
  '/clinics': typeof AppClinicsRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients': typeof AppPatientsRoute
  '/providers': typeof AppProvidersRoute
  '/settings': typeof AppSettingsRoute
  '/call-center/configuration': typeof AppCallCenterConfigurationRoute
  '/call-center/dashboard': typeof AppCallCenterDashboardRoute
  '/call-center/history': typeof AppCallCenterHistoryRoute
  '/call-center/knowledge-base': typeof AppCallCenterKnowledgeBaseRoute
  '/call-center/persona': typeof AppCallCenterPersonaRoute
  '/call-center/whatsapp': typeof AppCallCenterWhatsappRoute
  '/call-center/whatsapp-templates': typeof AppCallCenterWhatsappTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AppAppointmentsRoute
  '/calendar': typeof AppCalendarRoute
  '/call-center': typeof AppCallCenterRouteWithChildren
  '/clinics': typeof AppClinicsRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients': typeof AppPatientsRoute
  '/providers': typeof AppProvidersRoute
  '/settings': typeof AppSettingsRoute
  '/call-center/configuration': typeof AppCallCenterConfigurationRoute
  '/call-center/dashboard': typeof AppCallCenterDashboardRoute
  '/call-center/history': typeof AppCallCenterHistoryRoute
  '/call-center/knowledge-base': typeof AppCallCenterKnowledgeBaseRoute
  '/call-center/persona': typeof AppCallCenterPersonaRoute
  '/call-center/whatsapp': typeof AppCallCenterWhatsappRoute
  '/call-center/whatsapp-templates': typeof AppCallCenterWhatsappTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/call-center': typeof AppCallCenterRouteWithChildren
  '/_app/clinics': typeof AppClinicsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/providers': typeof AppProvidersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/call-center/configuration': typeof AppCallCenterConfigurationRoute
  '/_app/call-center/dashboard': typeof AppCallCenterDashboardRoute
  '/_app/call-center/history': typeof AppCallCenterHistoryRoute
  '/_app/call-center/knowledge-base': typeof AppCallCenterKnowledgeBaseRoute
  '/_app/call-center/persona': typeof AppCallCenterPersonaRoute
  '/_app/call-center/whatsapp': typeof AppCallCenterWhatsappRoute
  '/_app/call-center/whatsapp-templates': typeof AppCallCenterWhatsappTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/appointments'
    | '/calendar'
    | '/call-center'
    | '/clinics'
    | '/dashboard'
    | '/patients'
    | '/providers'
    | '/settings'
    | '/call-center/configuration'
    | '/call-center/dashboard'
    | '/call-center/history'
    | '/call-center/knowledge-base'
    | '/call-center/persona'
    | '/call-center/whatsapp'
    | '/call-center/whatsapp-templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/appointments'
    | '/calendar'
    | '/call-center'
    | '/clinics'
    | '/dashboard'
    | '/patients'
    | '/providers'
    | '/settings'
    | '/call-center/configuration'
    | '/call-center/dashboard'
    | '/call-center/history'
    | '/call-center/knowledge-base'
    | '/call-center/persona'
    | '/call-center/whatsapp'
    | '/call-center/whatsapp-templates'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/appointments'
    | '/_app/calendar'
    | '/_app/call-center'
    | '/_app/clinics'
    | '/_app/dashboard'
    | '/_app/patients'
    | '/_app/providers'
    | '/_app/settings'
    | '/_app/call-center/configuration'
    | '/_app/call-center/dashboard'
    | '/_app/call-center/history'
    | '/_app/call-center/knowledge-base'
    | '/_app/call-center/persona'
    | '/_app/call-center/whatsapp'
    | '/_app/call-center/whatsapp-templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinics': {
      id: '/_app/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof AppClinicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-center': {
      id: '/_app/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof AppCallCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-center/whatsapp-templates': {
      id: '/_app/call-center/whatsapp-templates'
      path: '/whatsapp-templates'
      fullPath: '/call-center/whatsapp-templates'
      preLoaderRoute: typeof AppCallCenterWhatsappTemplatesRouteImport
      parentRoute: typeof AppCallCenterRoute
    }
    '/_app/call-center/whatsapp': {
      id: '/_app/call-center/whatsapp'
      path: '/whatsapp'
      fullPath: '/call-center/whatsapp'
      preLoaderRoute: typeof AppCallCenterWhatsappRouteImport
      parentRoute: typeof AppCallCenterRoute
    }
    '/_app/call-center/persona': {
      id: '/_app/call-center/persona'
      path: '/persona'
      fullPath: '/call-center/persona'
      preLoaderRoute: typeof AppCallCenterPersonaRouteImport
      parentRoute: typeof AppCallCenterRoute
    }
    '/_app/call-center/knowledge-base': {
      id: '/_app/call-center/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/call-center/knowledge-base'
      preLoaderRoute: typeof AppCallCenterKnowledgeBaseRouteImport
      parentRoute: typeof AppCallCenterRoute
    }
    '/_app/call-center/history': {
      id: '/_app/call-center/history'
      path: '/history'
      fullPath: '/call-center/history'
      preLoaderRoute: typeof AppCallCenterHistoryRouteImport
      parentRoute: typeof AppCallCenterRoute
    }
    '/_app/call-center/dashboard': {
      id: '/_app/call-center/dashboard'
      path: '/dashboard'
      fullPath: '/call-center/dashboard'
      preLoaderRoute: typeof AppCallCenterDashboardRouteImport
      parentRoute: typeof AppCallCenterRoute
    }
    '/_app/call-center/configuration': {
      id: '/_app/call-center/configuration'
      path: '/configuration'
      fullPath: '/call-center/configuration'
      preLoaderRoute: typeof AppCallCenterConfigurationRouteImport
      parentRoute: typeof AppCallCenterRoute
    }
  }
}

interface AppCallCenterRouteChildren {
  AppCallCenterConfigurationRoute: typeof AppCallCenterConfigurationRoute
  AppCallCenterDashboardRoute: typeof AppCallCenterDashboardRoute
  AppCallCenterHistoryRoute: typeof AppCallCenterHistoryRoute
  AppCallCenterKnowledgeBaseRoute: typeof AppCallCenterKnowledgeBaseRoute
  AppCallCenterPersonaRoute: typeof AppCallCenterPersonaRoute
  AppCallCenterWhatsappRoute: typeof AppCallCenterWhatsappRoute
  AppCallCenterWhatsappTemplatesRoute: typeof AppCallCenterWhatsappTemplatesRoute
}

const AppCallCenterRouteChildren: AppCallCenterRouteChildren = {
  AppCallCenterConfigurationRoute: AppCallCenterConfigurationRoute,
  AppCallCenterDashboardRoute: AppCallCenterDashboardRoute,
  AppCallCenterHistoryRoute: AppCallCenterHistoryRoute,
  AppCallCenterKnowledgeBaseRoute: AppCallCenterKnowledgeBaseRoute,
  AppCallCenterPersonaRoute: AppCallCenterPersonaRoute,
  AppCallCenterWhatsappRoute: AppCallCenterWhatsappRoute,
  AppCallCenterWhatsappTemplatesRoute: AppCallCenterWhatsappTemplatesRoute,
}

const AppCallCenterRouteWithChildren = AppCallCenterRoute._addFileChildren(
  AppCallCenterRouteChildren,
)

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCallCenterRoute: typeof AppCallCenterRouteWithChildren
  AppClinicsRoute: typeof AppClinicsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCallCenterRoute: AppCallCenterRouteWithChildren,
  AppClinicsRoute: AppClinicsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
