/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProvidersRouteImport } from './routes/_app.providers'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClinicsRouteImport } from './routes/_app.clinics'
import { Route as AppCallCenterRouteImport } from './routes/_app.call-center'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicsRoute = AppClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AppRoute,
} as any)
const AppCallCenterRoute = AppCallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AppAppointmentsRoute
  '/call-center': typeof AppCallCenterRoute
  '/clinics': typeof AppClinicsRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients': typeof AppPatientsRoute
  '/providers': typeof AppProvidersRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/appointments': typeof AppAppointmentsRoute
  '/call-center': typeof AppCallCenterRoute
  '/clinics': typeof AppClinicsRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients': typeof AppPatientsRoute
  '/providers': typeof AppProvidersRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/call-center': typeof AppCallCenterRoute
  '/_app/clinics': typeof AppClinicsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/providers': typeof AppProvidersRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/appointments'
    | '/call-center'
    | '/clinics'
    | '/dashboard'
    | '/patients'
    | '/providers'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/appointments'
    | '/call-center'
    | '/clinics'
    | '/dashboard'
    | '/patients'
    | '/providers'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/appointments'
    | '/_app/call-center'
    | '/_app/clinics'
    | '/_app/dashboard'
    | '/_app/patients'
    | '/_app/providers'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers': {
      id: '/_app/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinics': {
      id: '/_app/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof AppClinicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-center': {
      id: '/_app/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof AppCallCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppCallCenterRoute: typeof AppCallCenterRoute
  AppClinicsRoute: typeof AppClinicsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppCallCenterRoute: AppCallCenterRoute,
  AppClinicsRoute: AppClinicsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
